let productArr = [
  { imageIndex:1,
    imageAddress:"content/1.webp",
    ratings: { stars: 4.5, noOfRating: 1300 },
    company: "Skybags",
    productName: "Kids Graphic Printed Backpack",
    actualPrice: 2198,
    discountPercent: 65,
    quantity:1
  },
  { imageIndex:2,
    imageAddress:'content/2.webp',
    ratings: { stars: 0, noOfRating: 0 },
    company: "Anouk",
    productName: "Girls Embellished Tiara",
    actualPrice: 1599,
    discountPercent: 72,
    quantity:1
  },
  { imageIndex:3,
    imageAddress:'content/3.webp',
    ratings: { stars: 4.4, noOfRating: 717 },
    company: "KLOTTHE",
    productName: "300 TC king 2 Pillow Covers",
    actualPrice: 3159,
    discountPercent: 87,
    quantity:1
  },
  { imageIndex:4,
    imageAddress:'content/4.webp',
    ratings: { stars: 4.1, noOfRating: 253 },
    company: "BAESD",
    productName: "Shorts",
    actualPrice: 1999,
    discountPercent: 75,
    quantity:1
  },
  { imageIndex:5,
    imageAddress:'content/5.webp',
    ratings: { stars: 4.3, noOfRating: 294 },
    company: "Shocknshop",
    productName: "Kids Multi Function Watch",
    actualPrice: 1499,
    discountPercent: 67,
    quantity:1
  },
  { imageIndex:6,
    imageAddress:'content/6.webp',
    ratings: { stars: 4.4, noOfRating: 1100 },
    company: "ariel",
    productName: "Girls Pack of 3 Basic briefs",
    actualPrice: 899,
    discountPercent:50 ,
    quantity:1
  },
  { imageIndex:7,
    imageAddress:'content/7.webp',
    ratings: { stars: 4.2, noOfRating: 1200 },
    company: "YK Disney",
    productName: "Girls Pack Of 2 Frozen Joggers",
    actualPrice: 2789,
    discountPercent: 77,
    quantity:1
  },
  { imageIndex:8,
    imageAddress:'content/8.webp',
    ratings: { stars: 3.9, noOfRating: 202 },
    company: "BASED",
    productName: "Pack Of 3 Pure Cotton Joggers",
    actualPrice: 1499,
    discountPercent: 70,
    quantity:1
  },
  { imageIndex:9,
    imageAddress:'content/9.webp',
    ratings: { stars: 4.5, noOfRating: 32 },
    company: "VAGHBHATT",
    productName: "Girls Embellished Tiara",
    actualPrice: 1199,
    discountPercent: 76,
    quantity:1
  },
];